In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
df_2 = df[['survived', 'pclass', 'age', 'parch']]
df_3 = df_2.fillna(df_2.mean())
df_3

     survived  pclass        age  parch
0           0       3  22.000000      0
1           1       1  38.000000      0
2           1       3  26.000000      0
3           1       1  35.000000      0
4           0       3  35.000000      0
..        ...     ...        ...    ...
886         0       2  27.000000      0
887         1       1  19.000000      0
888         0       3  29.699118      2
889         1       1  26.000000      0
890         0       3  32.000000      0

[891 rows x 4 columns]

In [6]:
x = df_3.drop('survived', axis = 1)
y = df_3['survived']

print('shape of x = ' , x.shape)
print('shape of y = ' , y. shape)

shape of x =  (891, 3)
shape of y =  (891,)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)
print('Shape of x_train = ' , x_train.shape)
print('Shape of x_train = ' , y_train.shape)
print('Shape of x_train = ' , x_test.shape)
print('Shape of x_train = ' , y_test.shape)

Shape of x_train =  (623, 3)
Shape of x_train =  (623,)
Shape of x_train =  (268, 3)
Shape of x_train =  (268,)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)
print('Shape of x_train = ' , x_train.shape)
print('Shape of x_train = ' , y_train.shape)
print('Shape of x_train = ' , x_test.shape)
print('Shape of x_train = ' , y_test.shape)

Shape of x_train =  (712, 3)
Shape of x_train =  (712,)
Shape of x_train =  (179, 3)
Shape of x_train =  (179,)

In [10]:
x_train

     pclass        age  parch
98        2  34.000000      1
2         3  26.000000      0
228       2  18.000000      0
676       3  24.500000      0
794       3  25.000000      0
..      ...        ...    ...
163       3  17.000000      0
468       3  29.699118      0
205       3   2.000000      1
388       3  29.699118      0
611       3  29.699118      0

[712 rows x 3 columns]

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 51)
print('Shape of x_train = ' , x_train.shape)
print('Shape of x_train = ' , y_train.shape)
print('Shape of x_train = ' , x_test.shape)
print('Shape of x_train = ' , y_test.shape)

Shape of x_train =  (712, 3)
Shape of x_train =  (712,)
Shape of x_train =  (179, 3)
Shape of x_train =  (179,)

In [12]:
x_train

     pclass        age  parch
770       3  24.000000      0
152       3  55.500000      0
731       3  11.000000      0
775       3  18.000000      0
324       3  29.699118      2
..      ...        ...    ...
528       3  39.000000      0
709       3  29.699118      1
736       3  48.000000      3
485       3  29.699118      1
57        3  28.500000      0

[712 rows x 3 columns]